#!/usr/bin/bash
cd $(pwd)
if [ $1 = unsort ]; then
  mv ./*/*/{*.flac,*.mp3} ./
  rmdir */* > /dev/null 2>&1
  rmdir * > /dev/null 2>&1
else
  for file in {*.flac,*.mp3}; do
    artist=`ffprobe -loglevel error -show_entries format_tags=artist -of default=noprint_wrappers=1:nokey=1 "$file"`
    artist="${artist// /_}"
    [ ! -d "$artist" ] && mkdir "$artist"
    album=`ffprobe -loglevel error -show_entries format_tags=album -of default=noprint_wrappers=1:nokey=1 "$file"`
    album="${album// /_}"
    [ ! -d "$artist/$album" ] && mkdir "$artist/$album"
    mv "$file" "$artist/$album/"
  done
fi
